version: '3'
services:
  php-fpm:
    container_name: ${CONTAINER_NAME}-php
    build:
      context: docker/php-fpm
    volumes:
      - ./:/var/www
    links:
      - mysql
    networks:
      self:
        ipv4_address: ${NETWORK_PHP}
  nginx:
    container_name: ${CONTAINER_NAME}-nginx
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      self:
        ipv4_address: ${NETWORK_NGINX}
  redis:
    image: redis:3.2
    container_name: ${CONTAINER_NAME}-redis
    networks:
      self:
        ipv4_address: ${NETWORK_REDIS}
  mysql:
    image: mysql:5.7
    container_name: ${CONTAINER_NAME}-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./docker/config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 20
    networks:
      self:
        ipv4_address: ${NETWORK_MYSQL}
  mailhog:
    build: ./docker/mailhog
    container_name: ${CONTAINER_NAME}-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      self:
        ipv4_address: ${NETWORK_MAILHOG}

networks:
  self:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}